name: 'Setup Mobile Environment'
description: 'Bootstraps Node, Java, and Android SDK'
inputs:
  api-level:
    description: 'Android API Level'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'automation/mobile/package-lock.json'
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Set Android Environment Paths
      shell: bash
      run: |
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_HOME/emulator" >> $GITHUB_PATH
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
    - name: Cache AVD
      uses: actions/cache@v4
      with:
        path: ~/.android/avd
        key: avd-${{ inputs.api-level }}
    - name: Make Scripts Executable
      shell: bash
      run: chmod +x ./automation/mobile/scripts/*.sh
    - name: Run Android Setup Script
      shell: bash
      env:
        API_LEVEL: ${{ inputs.api-level }}
      run: ./automation/mobile/scripts/setup-android.sh
